const specialtiesWithFocusAreas = [
  {
    specialty: "Bipolar",
    focusAreas: ["Type I", "Type II", "Cyclothymia", "Rapid Cycling"],
  },
  {
    specialty: "LGBTQ",
    focusAreas: [
      "Coming Out",
      "Gender Identity",
      "Sexual Orientation",
      "Discrimination",
      "Family Acceptance",
    ],
  },
  {
    specialty: "Medication/Prescribing",
    focusAreas: [
      "Antidepressants",
      "Mood Stabilizers",
      "Antipsychotics",
      "Anti-anxiety",
    ],
  },
  {
    specialty: "Suicide History/Attempts",
    focusAreas: [
      "Crisis Intervention",
      "Safety Planning",
      "Ideation Management",
      "Post-attempt Support",
    ],
  },
  {
    specialty: "General Mental Health",
    focusAreas: [
      "anxiety",
      "depression",
      "stress",
      "grief",
      "life transitions",
    ],
  },
  {
    specialty: "Men's issues",
    focusAreas: [
      "Anger Management",
      "Work-Life Balance",
      "Fatherhood",
      "Masculinity",
      "Emotional Expression",
    ],
  },
  {
    specialty: "Relationship Issues",
    focusAreas: ["family", "friends", "couple", "divorce", "communication"],
  },
  {
    specialty: "Trauma & PTSD",
    focusAreas: [
      "Combat",
      "Childhood Trauma",
      "Sexual Assault",
      "Natural Disasters",
      "Complex PTSD",
    ],
  },
  {
    specialty: "Personality disorders",
    focusAreas: [
      "Borderline",
      "Narcissistic",
      "Antisocial",
      "Avoidant",
      "Dependent",
    ],
  },
  {
    specialty: "Personal growth",
    focusAreas: [
      "Self-Esteem",
      "Goal Setting",
      "Mindfulness",
      "Self-Discovery",
      "Identity Development",
    ],
  },
  {
    specialty: "Substance use/abuse",
    focusAreas: [
      "Alcohol",
      "Opioids",
      "Stimulants",
      "Cannabis",
      "Recovery Support",
      "Relapse Prevention",
    ],
  },
  {
    specialty: "Pediatrics",
    focusAreas: [
      "Behavioral Issues",
      "Development",
      "School Problems",
      "Parenting Support",
      "Social Skills",
    ],
  },
  {
    specialty: "Women's issues",
    focusAreas: [
      "post-partum",
      "infertility",
      "family planning",
      "menopause",
      "pregnancy",
    ],
  },
  {
    specialty: "Chronic pain",
    focusAreas: [
      "Fibromyalgia",
      "Back Pain",
      "Migraines",
      "Pain Coping Strategies",
      "Neuropathy",
    ],
  },
  {
    specialty: "Weight loss & nutrition",
    focusAreas: [
      "Meal Planning",
      "Behavioral Change",
      "Metabolic Health",
      "Exercise",
      "Portion Control",
    ],
  },
  {
    specialty: "Eating disorders",
    focusAreas: [
      "Anorexia",
      "Bulimia",
      "Binge Eating",
      "Body Image",
      "Orthorexia",
    ],
  },
  {
    specialty: "Diabetic Diet and nutrition",
    focusAreas: [
      "Type 1",
      "Type 2",
      "Prediabetes",
      "Blood Sugar Management",
      "Carb Counting",
    ],
  },
  {
    specialty: "Coaching",
    focusAreas: ["leadership", "career", "academic", "wellness", "executive"],
  },
  {
    specialty: "Life coaching",
    focusAreas: [
      "Transitions",
      "Purpose",
      "Balance",
      "Accountability",
      "Goal Achievement",
    ],
  },
  {
    specialty: "Obsessive-compulsive disorders",
    focusAreas: [
      "Intrusive Thoughts",
      "Rituals",
      "Contamination",
      "Checking",
      "Hoarding",
    ],
  },
  {
    specialty: "Neuropsychological evaluations & testing",
    focusAreas: [
      "ADHD testing",
      "Cognitive Assessment",
      "Memory Testing",
      "IQ Testing",
    ],
  },
  {
    specialty: "Attention and Hyperactivity (ADHD)",
    focusAreas: [
      "Inattention",
      "Hyperactivity",
      "Executive Function",
      "Time Management",
      "Organization",
    ],
  },
  {
    specialty: "Sleep issues",
    focusAreas: [
      "Insomnia",
      "Sleep Apnea",
      "Nightmares",
      "Sleep Hygiene",
      "Circadian Rhythm",
    ],
  },
  {
    specialty: "Schizophrenia and psychotic disorders",
    focusAreas: [
      "Hallucinations",
      "Delusions",
      "Medication Management",
      "Reality Testing",
      "Coping Skills",
    ],
  },
  {
    specialty: "Learning disorders",
    focusAreas: [
      "Dyslexia",
      "Dyscalculia",
      "Processing Disorders",
      "IEP Support",
      "Reading Comprehension",
    ],
  },
  {
    specialty: "Domestic abuse",
    focusAreas: [
      "Physical Violence",
      "Emotional Abuse",
      "Safety Planning",
      "Trauma Recovery",
      "Legal Support",
    ],
  },
];

// Get random focus area IDs for advocates
const getRandomFocusAreaIds = (totalFocusAreas: number, count: number = 8) => {
  const ids = new Set<number>();
  while (ids.size < Math.min(count, totalFocusAreas)) {
    ids.add(Math.floor(Math.random() * totalFocusAreas) + 1);
  }
  return Array.from(ids);
};

// Bank of realistic first and last names (expand as needed)
const firstNames = [
  "James",
  "Mary",
  "John",
  "Patricia",
  "Robert",
  "Jennifer",
  "Michael",
  "Linda",
  "William",
  "Elizabeth",
  "David",
  "Barbara",
  "Richard",
  "Susan",
  "Joseph",
  "Jessica",
  "Thomas",
  "Sarah",
  "Charles",
  "Karen",
  "Christopher",
  "Nancy",
  "Daniel",
  "Lisa",
  "Matthew",
  "Betty",
  "Anthony",
  "Margaret",
  "Mark",
  "Sandra",
  "Donald",
  "Ashley",
  "Steven",
  "Kimberly",
  "Paul",
  "Emily",
  "Andrew",
  "Donna",
  "Joshua",
  "Michelle",
  "Kenneth",
  "Dorothy",
  "Kevin",
  "Carol",
  "Brian",
  "Amanda",
  "George",
  "Melissa",
  "Edward",
  "Deborah",
  "Ronald",
  "Stephanie",
  "Timothy",
  "Rebecca",
  "Jason",
  "Laura",
  "Jeffrey",
  "Sharon",
  "Ryan",
  "Cynthia",
  "Jacob",
  "Kathleen",
  "Gary",
  "Amy",
  "Nicholas",
  "Shirley",
  "Eric",
  "Angela",
  "Stephen",
  "Helen",
  "Jonathan",
  "Anna",
  "Larry",
  "Brenda",
  "Justin",
  "Pamela",
  "Scott",
  "Nicole",
  "Brandon",
  "Emma",
  "Benjamin",
  "Samantha",
  "Samuel",
  "Katherine",
  "Gregory",
  "Christine",
  "Frank",
  "Debra",
  "Alexander",
  "Rachel",
  "Raymond",
  "Catherine",
  "Patrick",
  "Carolyn",
  "Jack",
  "Janet",
  "Dennis",
  "Ruth",
  "Jerry",
  "Maria",
  "Tyler",
  "Heather",
  "Aaron",
  "Diane",
  "Jose",
  "Virginia",
  "Henry",
  "Julie",
  "Adam",
  "Joyce",
  "Douglas",
  "Victoria",
  "Nathan",
  "Olivia",
  "Peter",
  "Kelly",
  "Zachary",
  "Christina",
  "Kyle",
  "Lauren",
  "Walter",
  "Joan",
  "Harold",
  "Evelyn",
  "Jeremy",
  "Judith",
  "Ethan",
  "Megan",
  "Carl",
  "Andrea",
  "Keith",
  "Cheryl",
  "Roger",
  "Hannah",
  "Gerald",
  "Jacqueline",
  "Christian",
  "Martha",
  "Terry",
  "Gloria",
  "Sean",
  "Teresa",
  "Arthur",
  "Ann",
  "Austin",
  "Sara",
  "Noah",
  "Madison",
  "Lawrence",
  "Frances",
  "Jesse",
  "Kathryn",
  "Joe",
  "Janice",
  "Bryan",
  "Jean",
  "Billy",
  "Abigail",
  "Jordan",
  "Alice",
  "Albert",
  "Julia",
  "Dylan",
  "Judy",
  "Bruce",
  "Grace",
  "Willie",
  "Denise",
  "Gabriel",
  "Amber",
  "Alan",
  "Marilyn",
  "Juan",
  "Beverly",
  "Logan",
  "Danielle",
  "Wayne",
  "Theresa",
  "Ralph",
  "Sophia",
  "Roy",
  "Marie",
  "Eugene",
  "Diana",
  "Randy",
  "Brittany",
  "Vincent",
  "Natalie",
  "Russell",
  "Isabella",
  "Louis",
  "Charlotte",
  "Philip",
  "Rose",
  "Bobby",
  "Alexis",
  "Johnny",
  "Kayla",
  "Bradley",
  "Lillian",
  "Phillip",
  "Alyssa",
  "Victor",
  "Brooke",
  "Martin",
  "Ella",
  "Ernest",
  "Bailey",
  "Samuel",
  "Morgan",
  "Clarence",
  "Molly",
  "Leonard",
  "Peyton",
  "Craig",
  "Melanie",
  "Dale",
  "Aubrey",
  "Curtis",
  "Addison",
  "Norman",
  "Avery",
  "Allen",
  "Hailey",
  "Frederick",
  "Gabriella",
  "Shawn",
  "Brooklyn",
  "Rodney",
  "Alexa",
  "Edwin",
  "Kimberly",
  "Oscar",
  "Layla",
  "Miguel",
  "Scarlett",
  "Francis",
  "Camila",
  "Danny",
  "Paisley",
  // interviewers can add more if they want to test the capabilities of virtual scrolling and filtering functionality
];

const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Gutierrez",
  "Ortiz",
  "Morgan",
  "Cooper",
  "Peterson",
  "Bailey",
  "Reed",
  "Kelly",
  "Howard",
  "Ramos",
  "Kim",
  "Cox",
  "Ward",
  "Richardson",
  "Watson",
  "Brooks",
  "Chavez",
  "Wood",
  "James",
  "Bennett",
  "Gray",
  "Mendoza",
  "Ruiz",
  "Hughes",
  "Price",
  "Alvarez",
  "Castillo",
  "Sanders",
  "Patel",
  "Myers",
  "Long",
  "Ross",
  "Foster",
  "Jimenez",
  "Powell",
  "Jenkins",
  "Perry",
  "Russell",
  "Sullivan",
  "Bell",
  "Coleman",
  "Butler",
  "Henderson",
  "Barnes",
  "Gonzales",
  "Fisher",
  "Vasquez",
  "Simmons",
  "Romero",
  "Jordan",
  "Patterson",
  "Alexander",
  "Hamilton",
  "Graham",
  "Reynolds",
  "Griffin",
  "Wallace",
  "Moreno",
  "West",
  "Cole",
  "Hayes",
  "Bryant",
  "Herrera",
  "Gibson",
  "Ellis",
  "Tran",
  "Medina",
  "Aguilar",
  "Stevens",
  "Murray",
  "Ford",
  "Castro",
  "Marshall",
  "Owens",
  "Harrison",
  "Fernandez",
  "Mcdonald",
  "Woods",
  "Washington",
  "Kennedy",
  "Wells",
  "Vargas",
  "Henry",
  "Chen",
  "Freeman",
  "Webb",
  "Tucker",
  "Guzman",
  "Burns",
  "Crawford",
  "Olson",
  "Simpson",
  "Porter",
  "Hunter",
  "Gordon",
  "Mendez",
  "Silva",
  "Shaw",
  "Snyder",
  "Mason",
  "Dixon",
  "Munoz",
  "Hunt",
  "Hicks",
  "Holmes",
  "Palmer",
  "Wagner",
  "Black",
  "Robertson",
  "Boyd",
  "Rose",
  "Stone",
  "Salazar",
  "Fox",
  "Warren",
  "Mills",
  "Meyer",
  "Rice",
  "Schmidt",
  "Garza",
  "Daniels",
  "Ferguson",
  "Nichols",
  "Stephens",
  "Soto",
  "Weaver",
  "Ryan",
  "Gardner",
  "Payne",
  "Grant",
  "Dunn",
  "Kelley",
  "Spencer",
  "Hawkins",
  "Arnold",
  "Pierce",
  "Vazquez",
  "Hansen",
  "Peters",
  "Santos",
  "Hart",
  "Bradley",
  "Knight",
  "Elliott",
  "Cunningham",
  "Duncan",
  "Armstrong",
  "Hudson",
  "Carroll",
  "Lane",
  "Riley",
  "Andrews",
  "Alvarado",
  "Ray",
  "Delgado",
  "Berry",
  "Perkins",
  "Hoffman",
  "Johnston",
  "Matthews",
  "Pena",
  "Richards",
  "Contreras",
  "Willis",
  "Carpenter",
  "Lawrence",
  "Sandoval",
  "Guerrero",
  "George",
  "Chapman",
  "Rios",
  "Estrada",
  "Ortega",
  "Watkins",
  "Greene",
  "Nunez",
  "Wheeler",
  "Valdez",
  "Harper",
  "Burke",
  "Larson",
  "Santiago",
  "Maldonado",
  "Morrison",
  "Franklin",
  "Carlson",
  "Austin",
  "Dominguez",
  "Carr",
  "Lawson",
  "Jacobs",
  "O'Brien",
  "Lynch",
  "Singh",
  "Vega",
  "Bishop",
  "Montgomery",
  "Jameson",
  "Craig",
  "Sherman",
  "Raymond",
  "Fleming",
  "Bush",
  "Barker",
  // interviewers can add more if they want to test the capabilities of virtual scrolling and filtering functionality
];

// Cities and degrees for randomization
const cities = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "San Francisco",
  "Columbus",
  "Fort Worth",
  "Indianapolis",
  "Charlotte",
  "Seattle",
  "Denver",
  "Washington",
];

const degrees = ["MD", "PhD", "MSW"];

// Generate 100 advocates with randomized data
const advocateData = Array.from({ length: 100 }, (_, i) => ({
  firstName: firstNames[Math.floor(Math.random() * firstNames.length)],
  lastName: lastNames[Math.floor(Math.random() * lastNames.length)],
  city: cities[Math.floor(Math.random() * cities.length)],
  degree: degrees[Math.floor(Math.random() * degrees.length)],
  yearsOfExperience: Math.floor(Math.random() * 30) + 1,
  phoneNumber: 5550000000 + i,
}));

export { advocateData, specialtiesWithFocusAreas, getRandomFocusAreaIds };
